# Google Foobar Challenges

This repository contains my solutions to the Google Foobar coding challenges. Foobar is (?) Google's secret hiring challenge platform where engineers are invited to solve a series of increasingly difficult programming problems. I believe it's just an easter egg now...
